# Generated by Django 6.0.6 on 2026-06-15 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_mark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mark',
            old_name='subjects',
            new_name='subject',
        ),
    ]
